version: "3"

networks:
  example:

services:
  gw:
    build: ./
    image: examples/gw
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8030:8030
    networks:
      - example
    external_links:
      - asjard-etcd-1:etcd
      - asjard-jaeger-1:jaeger
      - asjard-pushgateway-1:pushgateway
      - asjard-consul-1:consul
