version: "3"
networks:
  example:

services:
  etcd:
    image: bitnami/etcd:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 2379:2379
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
  etcdkeeper:
    image: deltaprojects/etcdkeeper:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 8080:8080
  mariadb:
    image: mariadb
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: example-database
      TZ: "Asia/Shanghai"
  redis:
    image: redis
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 6379:6379
  jeager:
    image: jaegertracing/all-in-one:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 16686:16686
      - 4318:4318
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9441
  prometheus:
    image: bitnami/prometheus:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    volumes:
      - ./prometheus.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
    external_links:
      - asjard-pushgateway-1:pushgateway
  pushgateway:
    image: bitnami/pushgateway:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 9091:9091
    networks:
      - example
  consul:
    image: consul:1.15.4
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - example
  service-center-etcd:
    image: "quay.io/coreos/etcd:v3.5.15"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER: default=http://etcd:2380
    networks:
      - example
  service-center:
    image: servicecomb/service-center:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 30100:30100
    environment:
      BACKEND_ADDRESS: http://etcd:2379
    networks:
      - example
    depends_on:
      - service-center-etcd
    links:
      - service-center-etcd:etcd
  servicecomb-kie:
    # build: https://github.com/wksw/servicecomb-kie.git#master
    image: servicecomb/kie:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 30110:30110
    environment:
      DB_KIND: etcd
      DB_URI: http://etcd:2379
      # MONGODB_USER: kie
      # MONGODB_PWD: 123
      # MONGODB_ADDR: mongo:27017
    networks:
      - example
  servicecomb-ux:
    image: servicecomb/ux:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 4200:4200
    environment:
      SC_ADDRESS: http://service-center:30100
    networks:
      - example
    depends_on:
      - service-center
    links:
      - servicecomb-kie:kie
  # nacos:
  #   image: nacos/nacos-server:v2.4.1
  #   restart: always
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "10"
  #   environment:
  #     - PREFER_HOST_MODE=hostname
  #     - MODE=standalone
  #     - NACOS_AUTH_IDENTITY_KEY=serverIdentity
  #     - NACOS_AUTH_IDENTITY_VALUE=security
  #     - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
  #   ports:
  #     - "8848:8848"
  #     - "9848:9848"
  #   networks:
  #     - example
