version: "3"
networks:
  example:

services:
  etcd:
    image: bitnami/etcd:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 2379:2379
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
  etcdkeeper:
    image: deltaprojects/etcdkeeper:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 8080:8080
  mariadb:
    image: mariadb
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: example-database
      TZ: "Asia/Shanghai"
  redis:
    image: redis
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 6379:6379
  jeager:
    image: jaegertracing/all-in-one:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 16686:16686
      - 4318:4318
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9441
  prometheus:
    image: bitnami/prometheus:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    volumes:
      - ./prometheus.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
    external_links:
      - asjard-pushgateway-1:pushgateway
  pushgateway:
    image: bitnami/pushgateway:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 9091:9091
    networks:
      - example
  consul:
    image: consul:1.15.4
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - example
  # nacos:
  #   image: nacos/nacos-server:v2.4.1
  #   restart: always
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "10"
  #   environment:
  #     - PREFER_HOST_MODE=hostname
  #     - MODE=standalone
  #     - NACOS_AUTH_IDENTITY_KEY=serverIdentity
  #     - NACOS_AUTH_IDENTITY_VALUE=security
  #     - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
  #   ports:
  #     - "8848:8848"
  #     - "9848:9848"
  #   networks:
  #     - example
