asjard:
  service:
    ## 项目名称
    ## 一个项目下可能会有多个服务
    ## 不实时生效，修改后需重新启动服务
    app: examples
    ## 当前部署环境，例如: dev, sit, uat,rc,pro等
    environment: "dev"
    ## 部署区域,例如: east-1, east-2
    ## 表示不同地域，内网不互通，只能通过公网相互连接的不同区域
    region: "default"
    ## 可用区，例如: az-1,az-2
    ## 表示同一区域内，或者同一个机房内，可以内网互通
    avaliablezone: "default"
    ## 站点地址
    website: "https://github.com/asjard/${asjard.service.app}/${asjard.service.instance.name}"
    ## 服务描述
    desc: |
      ## 这里是服务描述
    ## 服务实例详情
    instance:
      ## 系统码
      systemCode: 100
      shareable: true
      ## 服务名称
      name: fileupload
      ## 服务版本
      version: 1.0.0
      ## 自定义服务源数据
      metadata:
        tenantName: ${asjard.service.app}
