// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: mysql.proto

package mysqlpb

import (
	context "context"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type MysqlAPI struct {
	UnimplementedMysqlServer
	client MysqlClient
}

func (api *MysqlAPI) Bootstrap() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.examples.name", "examples")).Conn()
	if err != nil {
		return err
	}
	api.client = NewMysqlClient(conn)
	return nil
}
func (api *MysqlAPI) Shutdown() {
}

// 创建
func (api *MysqlAPI) Create(ctx context.Context, in *CreateOrUpdateReq) (*emptypb.Empty, error) {
	return api.client.Create(ctx, in)
}

// 更新
func (api *MysqlAPI) Update(ctx context.Context, in *CreateOrUpdateReq) (*ExampleInfo, error) {
	return api.client.Update(ctx, in)
}

// 获取详情
func (api *MysqlAPI) Get(ctx context.Context, in *ReqWithName) (*ExampleInfo, error) {
	return api.client.Get(ctx, in)
}

// 查询
func (api *MysqlAPI) Search(ctx context.Context, in *SearchReq) (*ExampleList, error) {
	return api.client.Search(ctx, in)
}

// 删除
func (api *MysqlAPI) Del(ctx context.Context, in *ReqWithName) (*emptypb.Empty, error) {
	return api.client.Del(ctx, in)
}
func (api *MysqlAPI) RestServiceDesc() *rest.ServiceDesc {
	return &MysqlRestServiceDesc
}
