asjard:
  ## 数据相关配置
  database:
    mysql:
      dbs:
        default:
          dsn: root:my-secret-pw@tcp(127.0.0.1:3306)/exmple-database?charset=utf8&parseTime=True&loc=Local&timeout=5s&readTimeout=5s
          ## 数据库驱动
          ## mysql, postgres,sqlite,sqlserver,clickhouse
          ## ref: https://gorm.io/zh_CN/docs/connecting_to_the_database.html#PostgreSQL
          driver: mysql
          ## 驱动自定义配置
          options:
            ## 自定义驱动名称
            ## ref: https://gorm.io/docs/connecting_to_the_database.html#Customize-Driver
            driverName: ""
      ## 数据库连接配置
      options:
        maxIdleConns: 10
        maxOpenConns: 1001
        # connMaxIdleTime: 10
        # connMaxLifeTime: 2h
        ignoreRecordNotFoundError: false
        slowThreshold: 200ms
        debug: true
    redis:
      clients:
        default:
          address: 127.0.0.1:6379
    mongo:
      hosts:
        - "127.0.0.1:2370"
    etcd:
      clients:
        default:
          endpoints:
            - "127.0.0.1:2379"
