version: "3"

networks:
  example:

services:
  fileupload:
    build:
      context: .
      no_cache: true
    image: examples/fileupload
    restart: always
    ports:
      - 5030:5030
    networks:
      - example
    external_links:
      - asjard-jeager-1:jaeger
      - asjard-pushgateway-1:pushgateway
