// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: api/readme.proto

package readmepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Examples_Say_FullMethodName   = "/api.v1.readme.Examples/Say"
	Examples_Log_FullMethodName   = "/api.v1.readme.Examples/Log"
	Examples_Hello_FullMethodName = "/api.v1.readme.Examples/Hello"
	Examples_Call_FullMethodName  = "/api.v1.readme.Examples/Call"
)

// ExamplesClient is the client API for Examples service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExamplesClient interface {
	// 注释，描述这个接口的作用
	Say(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloReq, error)
	// sse请求
	Log(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Hello Example
	Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReq, error)
	// grpc请求
	Call(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloReq, error)
}

type examplesClient struct {
	cc grpc.ClientConnInterface
}

func NewExamplesClient(cc grpc.ClientConnInterface) ExamplesClient {
	return &examplesClient{cc}
}

func (c *examplesClient) Say(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloReq, error) {
	out := new(HelloReq)
	err := c.cc.Invoke(ctx, Examples_Say_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examplesClient) Log(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Examples_Log_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examplesClient) Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReq, error) {
	out := new(HelloReq)
	err := c.cc.Invoke(ctx, Examples_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examplesClient) Call(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloReq, error) {
	out := new(HelloReq)
	err := c.cc.Invoke(ctx, Examples_Call_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamplesServer is the server API for Examples service.
// All implementations must embed UnimplementedExamplesServer
// for forward compatibility
type ExamplesServer interface {
	// 注释，描述这个接口的作用
	Say(context.Context, *HelloReq) (*HelloReq, error)
	// sse请求
	Log(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Hello Example
	Hello(context.Context, *emptypb.Empty) (*HelloReq, error)
	// grpc请求
	Call(context.Context, *HelloReq) (*HelloReq, error)
	mustEmbedUnimplementedExamplesServer()
}

// UnimplementedExamplesServer must be embedded to have forward compatible implementations.
type UnimplementedExamplesServer struct {
}

func (UnimplementedExamplesServer) Say(context.Context, *HelloReq) (*HelloReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (UnimplementedExamplesServer) Log(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedExamplesServer) Hello(context.Context, *emptypb.Empty) (*HelloReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedExamplesServer) Call(context.Context, *HelloReq) (*HelloReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedExamplesServer) mustEmbedUnimplementedExamplesServer() {}

// UnsafeExamplesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamplesServer will
// result in compilation errors.
type UnsafeExamplesServer interface {
	mustEmbedUnimplementedExamplesServer()
}

func RegisterExamplesServer(s grpc.ServiceRegistrar, srv ExamplesServer) {
	s.RegisterService(&Examples_ServiceDesc, srv)
}

func _Examples_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamplesServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Examples_Say_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamplesServer).Say(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Examples_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamplesServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Examples_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamplesServer).Log(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Examples_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamplesServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Examples_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamplesServer).Hello(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Examples_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamplesServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Examples_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamplesServer).Call(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Examples_ServiceDesc is the grpc.ServiceDesc for Examples service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Examples_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.readme.Examples",
	HandlerType: (*ExamplesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Examples_Say_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _Examples_Log_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _Examples_Hello_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _Examples_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/readme.proto",
}
