// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.0
// - protoc             v5.27.0
// source: api/readmepb/readme.proto

package readmepb

import (
	status "github.com/asjard/asjard/core/status"
	validator "github.com/go-playground/validator"
	codes "google.golang.org/grpc/codes"
)

func (m *HelloReq_Obj) IsValid(fullMethod string) error {
	return nil
}

func (m *HelloReq_Configs) IsValid(fullMethod string) error {
	return nil
}

func (m *HelloReq_Instance) IsValid(fullMethod string) error {
	return nil
}

func (m *HelloReq) IsValid(fullMethod string) error {
	if err := m.Obj.IsValid(fullMethod); err != nil {
		return err
	}
	for _, fm := range m.Objs {
		if err := fm.IsValid(fullMethod); err != nil {
			return err
		}
	}
	if err := m.Configs.IsValid(fullMethod); err != nil {
		return err
	}
	v := validator.New()
	if err := v.Var(m.Page, "min=1"); err != nil {
		return status.Error(codes.InvalidArgument, "validation fail field 'Page' on 'min=1'")
	}
	if err := v.Var(m.Size, "max=200"); err != nil {
		return status.Error(codes.InvalidArgument, "validation fail field 'Size' on 'max=200'")
	}
	if err := m.Instance.IsValid(fullMethod); err != nil {
		return err
	}
	return nil
}
