// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: api/readmepb/readme.proto

package readmepb

import (
	context "context"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type ExamplesAPI struct {
	UnimplementedExamplesServer
	client ExamplesClient
}

func (api *ExamplesAPI) Start() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.readme.name", "readme")).Conn()
	if err != nil {
		return err
	}
	api.client = NewExamplesClient(conn)
	return nil
}
func (api *ExamplesAPI) Stop() {
}

// 注释，描述这个接口的作用
func (api *ExamplesAPI) Say(ctx context.Context, in *HelloReq) (*HelloReq, error) {
	return api.client.Say(ctx, in)
}

// sse请求
func (api *ExamplesAPI) Log(ctx context.Context, in *emptypb.Empty) (*emptypb.Empty, error) {
	return api.client.Log(ctx, in)
}

// Hello Example
func (api *ExamplesAPI) Hello(ctx context.Context, in *emptypb.Empty) (*HelloReq, error) {
	return api.client.Hello(ctx, in)
}
func (api *ExamplesAPI) RestServiceDesc() *rest.ServiceDesc {
	return &ExamplesRestServiceDesc
}
