// Code generated by protoc-gen-go-asynq. DO NOT EDIT.
// versions:
// - protoc-gen-go-asynq v1.3.0
// - protoc             v5.27.0
// source: api/serverpb/server.proto

package serverpb

import (
	context "context"
	server "github.com/asjard/asjard/core/server"
	xasynq "github.com/asjard/asjard/pkg/server/xasynq"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// 注释，描述这个接口的作用
func _Server_Say_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(HelloReq)
	if interceptor == nil {
		return srv.(ServerServer).Say(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Say_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Say(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// sse请求
func _Server_Log_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(emptypb.Empty)
	if interceptor == nil {
		return srv.(ServerServer).Log(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Log_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Log(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// grpc请求
func _Server_Call_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(HelloReq)
	if interceptor == nil {
		return srv.(ServerServer).Call(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Call_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Call(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 通过asynq接收异步请求
func _Server_Asynq_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(HelloReq)
	if interceptor == nil {
		return srv.(ServerServer).Asynq(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Asynq_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Asynq(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// ServerAsynqServiceDesc is the xasynq.ServiceDesc for Server service.
// It's only intended for direct use with xasynq.AddHandler,
// and not to be introspected or modified (even as a copy)
//
// 这里是server的描述
var ServerAsynqServiceDesc = xasynq.ServiceDesc{
	ServiceName: "api.v1.server.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []xasynq.MethodDesc{
		{
			Pattern: Server_Say_FullMethodName,
			Handler: _Server_Say_AsynqHandler,
		},
		{
			Pattern: Server_Log_FullMethodName,
			Handler: _Server_Log_AsynqHandler,
		},
		{
			Pattern: Server_Call_FullMethodName,
			Handler: _Server_Call_AsynqHandler,
		},
		{
			Pattern: Server_Asynq_FullMethodName,
			Handler: _Server_Asynq_AsynqHandler,
		},
	},
}
