// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: api/server.proto

package serverpb

import (
	context "context"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type ServerAPI struct {
	UnimplementedServerServer
	client ServerClient
}

func (api *ServerAPI) Bootstrap() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.server.name", "server")).Conn()
	if err != nil {
		return err
	}
	api.client = NewServerClient(conn)
	return nil
}
func (api *ServerAPI) Shutdown() {
}

// 注释，描述这个接口的作用
func (api *ServerAPI) Say(ctx context.Context, in *HelloReq) (*HelloReq, error) {
	return api.client.Say(ctx, in)
}

// rest请求
func (api *ServerAPI) Hello(ctx context.Context, in *emptypb.Empty) (*HelloReq, error) {
	return api.client.Hello(ctx, in)
}

// sse请求
func (api *ServerAPI) Log(ctx context.Context, in *emptypb.Empty) (*emptypb.Empty, error) {
	return api.client.Log(ctx, in)
}
func (api *ServerAPI) RestServiceDesc() *rest.ServiceDesc {
	return &ServerRestServiceDesc
}
