// Code generated by protoc-gen-go-asynq. DO NOT EDIT.
// versions:
// - protoc-gen-go-asynq v1.3.0
// - protoc             v5.27.0
// source: api/serverpb/server.proto

package serverpb

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	server "github.com/asjard/asjard/core/server"
	xasynq "github.com/asjard/asjard/pkg/server/xasynq"
	asynq "github.com/hibiken/asynq"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	sync "sync"
)

type ServerAsynqClientOptions struct {
	clientName string
}
type ServerAsynqClientOption func(opts *ServerAsynqClientOptions)

func ServerAsynqClientWithRedis(clientName string) ServerAsynqClientOption {
	return func(opts *ServerAsynqClientOptions) {
		if clientName != "" {
			opts.clientName = clientName
		}
	}
}

type ServerAsynqClient struct {
	*asynq.Client
	options *ServerAsynqClientOptions
}

var (
	serverAsynqClient     *ServerAsynqClient
	serverAsynqClientOnce sync.Once
)

func NewServerAsynqClient(opts ...ServerAsynqClientOption) *ServerAsynqClient {
	serverAsynqClientOnce.Do(func() {
		options := &ServerAsynqClientOptions{
			clientName: "default",
		}
		for _, opt := range opts {
			opt(options)
		}
		serverAsynqClient = &ServerAsynqClient{
			options: options,
		}
		bootstrap.AddBootstrap(serverAsynqClient)
	})
	return serverAsynqClient
}
func (c *ServerAsynqClient) Start() error {
	conn, err := xasynq.NewRedisConn(c.options.clientName)
	if err != nil {
		return err
	}
	c.Client = asynq.NewClient(conn)
	return nil
}
func (c *ServerAsynqClient) Stop() {}

// 注释，描述这个接口的作用
func (c *ServerAsynqClient) Say(ctx context.Context, in *HelloReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Server_Say_FullMethodName), payload, opts...), opts...)
}

// sse请求
func (c *ServerAsynqClient) Log(ctx context.Context, in *emptypb.Empty, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Server_Log_FullMethodName), payload, opts...), opts...)
}

// grpc请求
func (c *ServerAsynqClient) Call(ctx context.Context, in *HelloReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Server_Call_FullMethodName), payload, opts...), opts...)
}

// 通过asynq接收异步请求
func (c *ServerAsynqClient) Asynq(ctx context.Context, in *HelloReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Server_Asynq_FullMethodName), payload, opts...), opts...)
}

// 注释，描述这个接口的作用
func _Server_Say_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(HelloReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Say(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Say_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Say(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// sse请求
func _Server_Log_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(emptypb.Empty)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Log(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Log_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Log(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// grpc请求
func _Server_Call_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(HelloReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Call(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Call_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Call(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 通过asynq接收异步请求
func _Server_Asynq_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(HelloReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Asynq(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_Asynq_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ServerServer).Asynq(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// ServerAsynqServiceDesc is the xasynq.ServiceDesc for Server service.
// It's only intended for direct use with xasynq.AddHandler,
// and not to be introspected or modified (even as a copy)
//
// 这里是server的描述
var ServerAsynqServiceDesc = xasynq.ServiceDesc{
	ServiceName: "api.v1.server.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []xasynq.MethodDesc{
		{
			Pattern: Server_Say_FullMethodName,
			Handler: _Server_Say_AsynqHandler,
		},
		{
			Pattern: Server_Log_FullMethodName,
			Handler: _Server_Log_AsynqHandler,
		},
		{
			Pattern: Server_Call_FullMethodName,
			Handler: _Server_Call_AsynqHandler,
		},
		{
			Pattern: Server_Asynq_FullMethodName,
			Handler: _Server_Asynq_AsynqHandler,
		},
	},
}
