// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: api/serverpb/server.proto

package serverpb

import (
	status "github.com/asjard/asjard/core/status"
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
	codes "google.golang.org/grpc/codes"
)

func (m *HelloReq_Obj) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *HelloReq_Configs) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *HelloReq_Instance) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *HelloReq) IsValid(parentFieldName, fullMethod string) error {
	if m.Obj != nil {
		if err := m.Obj.IsValid(validatepb.ValidateFieldName(parentFieldName, "obj"), fullMethod); err != nil {
			return err
		}
	}
	for _, fm := range m.Objs {
		if err := fm.IsValid(validatepb.ValidateFieldName(parentFieldName, "objs"), fullMethod); err != nil {
			return err
		}
	}
	if m.Configs != nil {
		if err := m.Configs.IsValid(validatepb.ValidateFieldName(parentFieldName, "configs"), fullMethod); err != nil {
			return err
		}
	}
	v := validatepb.DefaultValidator
	if err := v.Var(m.Page, "max=1000"); err != nil {
		return status.Errorf(202, "validation field '%s' on 'max=1000' fail", validatepb.ValidateFieldName(parentFieldName, "page"))
	}
	if _, ok := HelloReq_Kind_name[int32(m.Kind)]; !ok {
		return status.Errorf(codes.InvalidArgument, "invalid %s", validatepb.ValidateFieldName(parentFieldName, "kind"))
	}
	if m.Instance != nil {
		if err := m.Instance.IsValid(validatepb.ValidateFieldName(parentFieldName, "instance"), fullMethod); err != nil {
			return err
		}
	}
	if err := v.Var(m.Email, "email"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'email' fail", validatepb.ValidateFieldName(parentFieldName, "email"))
	}
	return nil
}
