// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.0
// - protoc             v5.27.0
// source: api/serverpb/server.proto

package serverpb

import (
	status "github.com/asjard/asjard/core/status"
	validator "github.com/go-playground/validator"
	codes "google.golang.org/grpc/codes"
)

func (m *HelloReq_Obj) IsValid(fullMethod string) error {
	return nil
}

func (m *HelloReq_Configs) IsValid(fullMethod string) error {
	return nil
}

func (m *HelloReq_Instance) IsValid(fullMethod string) error {
	return nil
}

func (m *HelloReq) IsValid(fullMethod string) error {
	if err := m.Obj.IsValid(fullMethod); err != nil {
		return err
	}
	for _, fm := range m.Objs {
		if err := fm.IsValid(fullMethod); err != nil {
			return err
		}
	}
	if err := m.Configs.IsValid(fullMethod); err != nil {
		return err
	}
	v := validator.New()
	if err := v.Var(m.Page, "max=1000"); err != nil {
		return status.Error(202, "validation fail field 'Page' on 'max=1000'")
	}
	if err := m.Instance.IsValid(fullMethod); err != nil {
		return err
	}
	if err := v.Var(m.Email, "email"); err != nil {
		return status.Error(codes.InvalidArgument, "validation fail field 'Email' on 'email'")
	}
	return nil
}
