version: "3"

networks:
  example:

services:
  mysql:
    build:
      context: .
      no_cache: true
    image: examples/mysql
    restart: always
    ports:
      - 7030:7030
    networks:
      - example
    external_links:
      - asjard-etcd-1:etcd
      - asjard-mariadb-1:mariadb
      - asjard-redis-1:redis
      - asjard-jeager-1:jaeger
      - asjard-pushgateway-1:pushgateway
