version: "3"

networks:
  example:

services:
  mysql:
    build: ./
    image: examples/mysql
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    # ports:
    # - 7030:7030
    networks:
      - example
    external_links:
      - asjard-etcd-1:etcd
      - asjard-mariadb-1:mariadb
      - asjard-redis-1:redis
      - asjard-jeager-1:jaeger
      - asjard-pushgateway-1:pushgateway
