// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.0
// - protoc             v5.27.0
// source: api/mysqlpb/mysql.proto

package mysqlpb

func (m *SearchReq) IsValid(fullMethod string) error {
	return nil
}

func (m *CreateOrUpdateReq) IsValid(fullMethod string) error {
	return nil
}

func (m *ReqWithName) IsValid(fullMethod string) error {
	return nil
}

func (m *ExampleInfo) IsValid(fullMethod string) error {
	return nil
}

func (m *ExampleList) IsValid(fullMethod string) error {
	for _, fm := range m.List {
		if err := fm.IsValid(fullMethod); err != nil {
			return err
		}
	}
	return nil
}
