// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: api/mysqlpb/mysql.proto

package mysqlpb

import (
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
)

func (m *SearchReq) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *CreateOrUpdateReq) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *ReqWithName) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *ExampleInfo) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *ExampleList) IsValid(parentFieldName, fullMethod string) error {
	for _, fm := range m.List {
		if err := fm.IsValid(validatepb.ValidateFieldName(parentFieldName, "list"), fullMethod); err != nil {
			return err
		}
	}
	return nil
}
