// Code generated by protoc-gen-go-asynq. DO NOT EDIT.
// versions:
// - protoc-gen-go-asynq v1.3.0
// - protoc             v5.27.0
// source: api/mysqlpb/mysql.proto

package mysqlpb

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	server "github.com/asjard/asjard/core/server"
	xasynq "github.com/asjard/asjard/pkg/server/xasynq"
	asynq "github.com/hibiken/asynq"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

type MysqlAsynqClientOptions struct {
	clientName string
}
type MysqlAsynqClientOption func(opts *MysqlAsynqClientOptions)

func MysqlAsynqClientWithRedis(clientName string) MysqlAsynqClientOption {
	return func(opts *MysqlAsynqClientOptions) {
		if clientName != "" {
			opts.clientName = clientName
		}
	}
}

type MysqlAsynqClient struct {
	*asynq.Client
	options *MysqlAsynqClientOptions
}

var (
	mysqlAsynqClient     *MysqlAsynqClient
	mysqlAsynqClientOnce sync.Once
)

func NewMysqlAsynqClient(opts ...MysqlAsynqClientOption) *MysqlAsynqClient {
	mysqlAsynqClientOnce.Do(func() {
		options := &MysqlAsynqClientOptions{
			clientName: "default",
		}
		for _, opt := range opts {
			opt(options)
		}
		mysqlAsynqClient = &MysqlAsynqClient{
			options: options,
		}
		bootstrap.AddBootstrap(mysqlAsynqClient)
	})
	return mysqlAsynqClient
}
func (c *MysqlAsynqClient) Start() error {
	conn, err := xasynq.NewRedisConn(c.options.clientName)
	if err != nil {
		return err
	}
	c.Client = asynq.NewClient(conn)
	return nil
}
func (c *MysqlAsynqClient) Stop() {}

// 创建
func (c *MysqlAsynqClient) Create(ctx context.Context, in *CreateOrUpdateReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Mysql_Create_FullMethodName), payload, opts...), opts...)
}

// 更新
func (c *MysqlAsynqClient) Update(ctx context.Context, in *CreateOrUpdateReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Mysql_Update_FullMethodName), payload, opts...), opts...)
}

// 获取详情
func (c *MysqlAsynqClient) Get(ctx context.Context, in *ReqWithName, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Mysql_Get_FullMethodName), payload, opts...), opts...)
}

// 查询
func (c *MysqlAsynqClient) Search(ctx context.Context, in *SearchReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Mysql_Search_FullMethodName), payload, opts...), opts...)
}

// 删除
func (c *MysqlAsynqClient) Del(ctx context.Context, in *ReqWithName, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(Mysql_Del_FullMethodName), payload, opts...), opts...)
}

// 创建
func _Mysql_Create_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(CreateOrUpdateReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).Create(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mysql_Create_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(MysqlServer).Create(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 更新
func _Mysql_Update_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(CreateOrUpdateReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).Update(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mysql_Update_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(MysqlServer).Update(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 获取详情
func _Mysql_Get_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(ReqWithName)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).Get(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mysql_Get_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(MysqlServer).Get(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 查询
func _Mysql_Search_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(SearchReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).Search(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mysql_Search_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(MysqlServer).Search(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 删除
func _Mysql_Del_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(ReqWithName)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).Del(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mysql_Del_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(MysqlServer).Del(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// MysqlAsynqServiceDesc is the xasynq.ServiceDesc for Mysql service.
// It's only intended for direct use with xasynq.AddHandler,
// and not to be introspected or modified (even as a copy)
var MysqlAsynqServiceDesc = xasynq.ServiceDesc{
	ServiceName: "api.v1.mysql.Mysql",
	HandlerType: (*MysqlServer)(nil),
	Methods: []xasynq.MethodDesc{
		{
			Pattern: Mysql_Create_FullMethodName,
			Handler: _Mysql_Create_AsynqHandler,
		},
		{
			Pattern: Mysql_Update_FullMethodName,
			Handler: _Mysql_Update_AsynqHandler,
		},
		{
			Pattern: Mysql_Get_FullMethodName,
			Handler: _Mysql_Get_AsynqHandler,
		},
		{
			Pattern: Mysql_Search_FullMethodName,
			Handler: _Mysql_Search_AsynqHandler,
		},
		{
			Pattern: Mysql_Del_FullMethodName,
			Handler: _Mysql_Del_AsynqHandler,
		},
	},
}
