// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: api/file.proto

package filepb

import (
	context "context"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type FileAPI struct {
	UnimplementedFileServer
	client FileClient
}

func (api *FileAPI) Bootstrap() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.file.name", "file")).Conn()
	if err != nil {
		return err
	}
	api.client = NewFileClient(conn)
	return nil
}
func (api *FileAPI) Shutdown() {
}

// 文件上传
func (api *FileAPI) Upload(ctx context.Context, in *UploadReq) (*UploadResp, error) {
	return api.client.Upload(ctx, in)
}

// 文件下载
func (api *FileAPI) Download(ctx context.Context, in *DownloadReq) (*emptypb.Empty, error) {
	return api.client.Download(ctx, in)
}
func (api *FileAPI) RestServiceDesc() *rest.ServiceDesc {
	return &FileRestServiceDesc
}
