// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.0
// - protoc             v5.27.0
// source: api/filepb/file.proto

package filepb

func (m *UploadReq) IsValid(fullMethod string) error {
	return nil
}

func (m *UploadResp) IsValid(fullMethod string) error {
	return nil
}

func (m *DownloadReq) IsValid(fullMethod string) error {
	return nil
}
