// Code generated by protoc-gen-go-asynq. DO NOT EDIT.
// versions:
// - protoc-gen-go-asynq v1.3.0
// - protoc             v5.27.0
// source: api/filepb/file.proto

package filepb

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	server "github.com/asjard/asjard/core/server"
	xasynq "github.com/asjard/asjard/pkg/server/xasynq"
	asynq "github.com/hibiken/asynq"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

type FileAsynqClientOptions struct {
	clientName string
}
type FileAsynqClientOption func(opts *FileAsynqClientOptions)

func FileAsynqClientWithRedis(clientName string) FileAsynqClientOption {
	return func(opts *FileAsynqClientOptions) {
		if clientName != "" {
			opts.clientName = clientName
		}
	}
}

type FileAsynqClient struct {
	*asynq.Client
	options *FileAsynqClientOptions
}

var (
	fileAsynqClient     *FileAsynqClient
	fileAsynqClientOnce sync.Once
)

func NewFileAsynqClient(opts ...FileAsynqClientOption) *FileAsynqClient {
	fileAsynqClientOnce.Do(func() {
		options := &FileAsynqClientOptions{
			clientName: "default",
		}
		for _, opt := range opts {
			opt(options)
		}
		fileAsynqClient = &FileAsynqClient{
			options: options,
		}
		bootstrap.AddBootstrap(fileAsynqClient)
	})
	return fileAsynqClient
}
func (c *FileAsynqClient) Start() error {
	conn, err := xasynq.NewRedisConn(c.options.clientName)
	if err != nil {
		return err
	}
	c.Client = asynq.NewClient(conn)
	return nil
}
func (c *FileAsynqClient) Stop() {}

// 文件上传
func (c *FileAsynqClient) Upload(ctx context.Context, in *UploadReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(File_Upload_FullMethodName), payload, opts...), opts...)
}

// 文件下载
func (c *FileAsynqClient) Download(ctx context.Context, in *DownloadReq, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	payload, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}
	return c.EnqueueContext(ctx, asynq.NewTask(xasynq.Pattern(File_Download_FullMethodName), payload, opts...), opts...)
}

// 文件上传
func _File_Upload_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(UploadReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).Upload(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_Upload_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FileServer).Upload(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 文件下载
func _File_Download_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(DownloadReq)
	if err := proto.Unmarshal(ctx.Payload(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).Download(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_Download_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FileServer).Download(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// FileAsynqServiceDesc is the xasynq.ServiceDesc for File service.
// It's only intended for direct use with xasynq.AddHandler,
// and not to be introspected or modified (even as a copy)
var FileAsynqServiceDesc = xasynq.ServiceDesc{
	ServiceName: "api.v1.file.File",
	HandlerType: (*FileServer)(nil),
	Methods: []xasynq.MethodDesc{
		{
			Pattern: File_Upload_FullMethodName,
			Handler: _File_Upload_AsynqHandler,
		},
		{
			Pattern: File_Download_FullMethodName,
			Handler: _File_Download_AsynqHandler,
		},
	},
}
