// Code generated by protoc-gen-go-asynq. DO NOT EDIT.
// versions:
// - protoc-gen-go-asynq v1.3.0
// - protoc             v5.27.0
// source: api/filepb/file.proto

package filepb

import (
	context "context"
	server "github.com/asjard/asjard/core/server"
	xasynq "github.com/asjard/asjard/pkg/server/xasynq"
)

// 文件上传
func _File_Upload_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(UploadReq)
	if interceptor == nil {
		return srv.(FileServer).Upload(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_Upload_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FileServer).Upload(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 文件下载
func _File_Download_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(DownloadReq)
	if interceptor == nil {
		return srv.(FileServer).Download(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_Download_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FileServer).Download(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// FileAsynqServiceDesc is the xasynq.ServiceDesc for File service.
// It's only intended for direct use with xasynq.AddHandler,
// and not to be introspected or modified (even as a copy)
var FileAsynqServiceDesc = xasynq.ServiceDesc{
	ServiceName: "api.v1.file.File",
	HandlerType: (*FileServer)(nil),
	Methods: []xasynq.MethodDesc{
		{
			Pattern: File_Upload_FullMethodName,
			Handler: _File_Upload_AsynqHandler,
		},
		{
			Pattern: File_Download_FullMethodName,
			Handler: _File_Download_AsynqHandler,
		},
	},
}
