// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: api/filepb/file.proto

package filepb

// IsValid Params validate
// 上传请求
func (m *UploadReq) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// 上传返回
func (m *UploadResp) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// 下载请求
func (m *DownloadReq) IsValid(parentFieldName, fullMethod string) error {
	return nil
}
