// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.0
// - protoc             v5.27.0
// source: api/cipherpb/cipher.proto

package cipherpb

func (m *DecryptResp) IsValid(fullMethod string) error {
	return nil
}

func (m *EncryptReq) IsValid(fullMethod string) error {
	return nil
}

func (m *EncryptResp) IsValid(fullMethod string) error {
	return nil
}
