// Code generated by protoc-gen-go-asynq. DO NOT EDIT.
// versions:
// - protoc-gen-go-asynq v1.3.0
// - protoc             v5.27.0
// source: api/cipherpb/cipher.proto

package cipherpb

import (
	context "context"
	server "github.com/asjard/asjard/core/server"
	xasynq "github.com/asjard/asjard/pkg/server/xasynq"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// 加密
func _Cipher_Encrypt_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(EncryptReq)
	if interceptor == nil {
		return srv.(CipherServer).Encrypt(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cipher_Encrypt_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(CipherServer).Encrypt(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// 解密
func _Cipher_Decrypt_AsynqHandler(ctx *xasynq.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(emptypb.Empty)
	if interceptor == nil {
		return srv.(CipherServer).Decrypt(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cipher_Decrypt_FullMethodName,
		Protocol:   xasynq.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(CipherServer).Decrypt(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// CipherAsynqServiceDesc is the xasynq.ServiceDesc for Cipher service.
// It's only intended for direct use with xasynq.AddHandler,
// and not to be introspected or modified (even as a copy)
//
// Cipher 加解密相关接口
var CipherAsynqServiceDesc = xasynq.ServiceDesc{
	ServiceName: "api.v1.cipher.Cipher",
	HandlerType: (*CipherServer)(nil),
	Methods: []xasynq.MethodDesc{
		{
			Pattern: Cipher_Encrypt_FullMethodName,
			Handler: _Cipher_Encrypt_AsynqHandler,
		},
		{
			Pattern: Cipher_Decrypt_FullMethodName,
			Handler: _Cipher_Decrypt_AsynqHandler,
		},
	},
}
