// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: api/cipherpb/cipher.proto

package cipherpb

// IsValid Params validate
// 加解密示例返回
func (m *DecryptResp) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// 加密请求
func (m *EncryptReq) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// 加密返回
func (m *EncryptResp) IsValid(parentFieldName, fullMethod string) error {
	return nil
}
